"""Private plotting constants for the mpl backend."""

DEFAULT_DPI = 100.0
ANIMATION_FRAME_DRAIN_LIMIT = 100
WINDOWED_QUEUE_DRAIN_LIMIT = 50
RELATION_TIMER_INTERVAL_MS = 30
AXIS_MIN_MAGNITUDE = 1.0e-9
AXIS_DECAY_FACTOR = 0.995
AXIS_PADDING_FACTOR = 1.08
XY_PADDING_RATIO = 0.1
